name: compile and deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/main.yml"
      - "GitHubActionsDemoApp/**"
      - "Tests/**"

env:
  DOTNET_VERSION: 8.0.x
  PROJECT: GithubActionsDemoApp/GithubActionsDemoApp.csproj

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Getting the code
        uses: actions/checkout@v4.2.2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Gtetting the dependencies
        run: dotnet restore

      - name: Compile
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build
        
      - name: Publish
        run: dotnet publish ${{ env.PROJECT }} -c Release -o myapp --runtime win-x86

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          path: ./myapp
          name: build
          
      - name: Zip
        run: zip -r myapp.zip ./myapp
        
      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ./myapp.zip
          body: "Our application"
          tag_name: ${{ github.ref_name }}
        
