name: matrix-worflow

on:
  workflow_dispatch

jobs:
  matrix-job:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]
      steps:
      - name: Run the matrix strategy
        run: |
        echo "${{ matrix.os}}"
        echo "${{ matrix.version}}"
